#!/usr/bin/env python3
"""
convert_goindol_logo.py — converte la marquee Goindol in header RGB565 RAW
per il carosello di SPINNERINO WIFI.

Output: 224x96 RGB565 byte-swap, STESSA dimensione/fitting del logo Gigas 2
(scala all'80% del canvas mantenendo l'ASPECT RATIO, centrato su nero).
Richiesta utente 2026-06-29: "dimensione come gigas 2, deve rimanere il suo
aspect ratio".

La sorgente e' una foto della marquee con largo bordo bianco: viene fatto
l'AUTOCROP del bianco prima del fit, cosi' il logo riempie l'80% del canvas.
"""
from PIL import Image, ImageChops
import os
from pathlib import Path

LOGO_W, LOGO_H = 224, 96
# Path portabili: marquee e logo.h dentro ../machines/goindol/. Eseguire da ROM_CONVERTER/.
SRC = str((Path.cwd() / ".." / "machines" / "goindol" / "goindol_marquee.jpeg").resolve())
OUT = str((Path.cwd() / ".." / "machines" / "goindol" / "goindol_logo.h").resolve())


def rgb888_to_rgb565_swapped(r, g, b):
    r5 = (r >> 3) & 0x1F
    g6 = (g >> 2) & 0x3F
    b5 = (b >> 3) & 0x1F
    rgb565 = (r5 << 11) | (g6 << 5) | b5
    return ((rgb565 >> 8) & 0xFF) | ((rgb565 & 0xFF) << 8)


def autocrop_white(img, thresh=12):
    """Rimuove il bordo (quasi) bianco attorno alla marquee."""
    rgb = img.convert('RGB')
    bg = Image.new('RGB', rgb.size, (255, 255, 255))
    diff = ImageChops.difference(rgb, bg)
    # add scale/offset to ignore lieve rumore JPEG vicino al bianco
    diff = ImageChops.add(diff, diff, 2.0, -thresh)
    bbox = diff.getbbox()
    return img.crop(bbox) if bbox else img


def fit_into(img, target_w, target_h, scale=0.80):
    inner_w = int(target_w * scale)
    inner_h = int(target_h * scale)
    w, h = img.size
    aspect = w / h
    inner_aspect = inner_w / inner_h
    if aspect > inner_aspect:
        new_w = inner_w
        new_h = int(inner_w / aspect)
    else:
        new_h = inner_h
        new_w = int(inner_h * aspect)
    resized = img.resize((new_w, new_h), Image.LANCZOS)
    canvas = Image.new('RGB', (target_w, target_h), (0, 0, 0))
    pos = ((target_w - new_w) // 2, (target_h - new_h) // 2)
    if resized.mode == 'RGBA':
        canvas.paste(resized, pos, resized)
    else:
        canvas.paste(resized, pos)
    return canvas


def write_header(path, var_name, pixels):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w') as f:
        f.write("// Auto-generated by convert_goindol_logo.py\n")
        f.write(f"// {LOGO_W}x{LOGO_H} RGB565 byte-swap (ESP32 SPI BE), RAW format\n")
        f.write(f"#define {var_name.upper()}_W {LOGO_W}\n")
        f.write(f"#define {var_name.upper()}_H {LOGO_H}\n")
        f.write(f"const unsigned short {var_name}[{LOGO_W}*{LOGO_H}] PROGMEM = {{\n")
        for i in range(0, len(pixels), 12):
            chunk = pixels[i:i+12]
            f.write("  " + ", ".join(f"0x{p:04X}" for p in chunk) + ",\n")
        f.write("};\n")
    print(f"  wrote {path}  ({len(pixels)} px = {len(pixels)*2} bytes)")


def main():
    print(f"[goindol_logo] {SRC}")
    img = Image.open(SRC)
    print(f"  source: {img.size} mode={img.mode}")
    if img.mode not in ('RGB', 'RGBA'):
        img = img.convert('RGB')
    img = autocrop_white(img)
    print(f"  dopo autocrop: {img.size} aspect={img.size[0]/img.size[1]:.3f}")
    canvas = fit_into(img, LOGO_W, LOGO_H)
    pixels = [rgb888_to_rgb565_swapped(r, g, b) for (r, g, b) in canvas.getdata()]
    write_header(OUT, "goindol_logo", pixels)
    print("Done!")


if __name__ == '__main__':
    main()
