#!/usr/bin/env python3
"""
convert_bombbee_logo.py — genera machines/bombbee/bombbee_logo.h dal marquee.

Formato logo SPINNERINO: 224x96 RGB565 byte-swap (ESP32 SPI BE), RAW.
Regola utente per LOGHI DA IMMAGINE REALE: stretch-fit a (W,H) con LANCZOS,
NIENTE taglio, NIENTE bordi — anche se deforma (riempie tutto il frame).

Sorgente: "bombbee logo.jpg" (marquee Namco). Cerca prima il path noto, poi
fallback nella cwd / ROMS.
"""
from PIL import Image, ImageOps
from pathlib import Path
import os, sys

W, H = 224, 96
VAR  = "bombbee_logo"
DEF  = "BOMBBEE_LOGO"
OUT  = str((Path.cwd() / ".." / "machines" / "bombbee" / "bombbee_logo.h").resolve())

CANDIDATES = [
    r"C:\Users\Tecnico\Desktop\PROGETTI SH\SPINNERINO WIFI\bombbee logo.jpg",
    str((Path.cwd() / "bombbee logo.jpg").resolve()),
    str((Path.cwd() / ".." / "ROMS" / "bombbee logo.jpg").resolve()),
    str((Path.cwd() / "bombbee_logo.jpg").resolve()),
]

def find_src():
    for c in CANDIDATES:
        if os.path.exists(c):
            return c
    return None

def main():
    src = find_src()
    if not src:
        print("!! immagine sorgente non trovata. Cercato:", file=sys.stderr)
        for c in CANDIDATES:
            print("   ", c, file=sys.stderr)
        sys.exit(1)
    print(f"[convert_bombbee_logo] sorgente: {src}")

    # Mantieni l'ASPECT RATIO originale del marquee (no stretch): fit "contain"
    # dentro WxH, centrato su canvas nero. L'immagine risulta piu' piccola e
    # schiacciata (l'originale e' molto piu' largo del frame 224x96).
    base = Image.open(src).convert("RGB")
    fitted = ImageOps.contain(base, (W, H), Image.LANCZOS)   # preserva proporzioni
    img = Image.new("RGB", (W, H), (0, 0, 0))
    fw, fh = fitted.size
    img.paste(fitted, ((W - fw) // 2, (H - fh) // 2))
    px = img.load()

    # anteprima PNG opzionale (accanto allo script, non nella cartella firmware)
    try:
        img.save(str(Path(__file__).parent / "bombbee_logo_preview.png"))
    except Exception:
        pass

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("// Auto-generated by convert_bombbee_logo.py\n")
        f.write("// 224x96 RGB565 byte-swap (ESP32 SPI BE), RAW format\n")
        f.write(f"#define {DEF}_W {W}\n")
        f.write(f"#define {DEF}_H {H}\n")
        f.write(f"const unsigned short {VAR}[{W}*{H}] PROGMEM = {{\n")
        vals = []
        for y in range(H):
            for x in range(W):
                r, g, b = px[x, y]
                c = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)  # RGB565
                sw = ((c & 0xFF) << 8) | (c >> 8)                      # byte-swap
                vals.append(sw)
        for i in range(0, len(vals), 12):
            chunk = vals[i:i+12]
            line = ", ".join(f"0x{v:04X}" for v in chunk)
            f.write("  " + line + ("," if i + 12 < len(vals) else "") + "\n")
        f.write("};\n")
    print(f"  wrote {OUT}  ({W}x{H} = {W*H} px)")
    print("Done!")

if __name__ == "__main__":
    main()
