#!/usr/bin/env python3
"""
convert_pang_logo.py — converte il logo PANG in header RGB565 RAW per il
carosello di SPINNERINO.

Output: 224x96 RGB565 byte-swap (ESP32 SPI BE), formato RAW (come tutti gli
altri *_logo.h del progetto, indicizzati da boot_menu.cpp come logo[row*224+col]).

Stessa dimensione/fitting del logo GIGAS 2 (richiesta utente): scala all'80%
della canvas MANTENENDO l'ASPECT RATIO, centrato su nero. La sorgente
pang_logo_src.png e' il logo PANG reale (con sfondo trasparente/bianco): viene
fatto l'autocrop dello sfondo prima del fit, cosi' il logo riempie l'80%.
Path portabili (eseguire da ROM_CONVERTER/).
"""
from PIL import Image, ImageChops
import os
from pathlib import Path

LOGO_W, LOGO_H = 224, 96
SCALE = 0.80                       # come Gigas 2 / Goindol
SRC = str((Path.cwd() / ".." / "machines" / "pang" / "pang_logo_src.png").resolve())
OUT = str((Path.cwd() / ".." / "machines" / "pang" / "pang_logo.h").resolve())


def rgb888_to_rgb565_swapped(r, g, b):
    r5 = (r >> 3) & 0x1F
    g6 = (g >> 2) & 0x3F
    b5 = (b >> 3) & 0x1F
    rgb565 = (r5 << 11) | (g6 << 5) | b5
    return ((rgb565 >> 8) & 0xFF) | ((rgb565 & 0xFF) << 8)


def autocrop(img):
    """Crop dello sfondo: usa l'alpha se presente, altrimenti il bordo bianco."""
    if img.mode == 'RGBA':
        alpha = img.split()[3]
        bbox = alpha.getbbox()
        if bbox:
            return img.crop(bbox)
    rgb = img.convert('RGB')
    bg = Image.new('RGB', rgb.size, (255, 255, 255))
    diff = ImageChops.difference(rgb, bg)
    diff = ImageChops.add(diff, diff, 2.0, -12)
    bbox = diff.getbbox()
    return img.crop(bbox) if bbox else img


def fit_into(img, target_w, target_h, scale=SCALE):
    inner_w = int(target_w * scale)
    inner_h = int(target_h * scale)
    w, h = img.size
    aspect = w / h
    inner_aspect = inner_w / inner_h
    if aspect > inner_aspect:
        new_w = inner_w
        new_h = max(1, int(inner_w / aspect))
    else:
        new_h = inner_h
        new_w = max(1, int(inner_h * aspect))
    resized = img.resize((new_w, new_h), Image.LANCZOS)
    canvas = Image.new('RGB', (target_w, target_h), (0, 0, 0))
    pos = ((target_w - new_w) // 2, (target_h - new_h) // 2)
    if resized.mode == 'RGBA':
        canvas.paste(resized, pos, resized)        # compositing su nero via alpha
    else:
        canvas.paste(resized, pos)
    return canvas


def write_header(path, var_name, pixels):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w') as f:
        f.write("#ifndef PANG_LOGO_H\n#define PANG_LOGO_H\n")
        f.write("#include <pgmspace.h>\n")
        f.write("// Auto-generated by convert_pang_logo.py\n")
        f.write(f"// {LOGO_W}x{LOGO_H} RGB565 byte-swap (ESP32 SPI BE), RAW format\n")
        f.write(f"const unsigned short {var_name}[{LOGO_W}*{LOGO_H}] PROGMEM = {{\n")
        for i in range(0, len(pixels), 12):
            chunk = pixels[i:i+12]
            f.write("  " + ", ".join(f"0x{p:04X}" for p in chunk) + ",\n")
        f.write("};\n")
        f.write("#endif // PANG_LOGO_H\n")
    print(f"  wrote {path}  ({len(pixels)} px = {len(pixels)*2} bytes)")


def main():
    print(f"[pang_logo] {SRC}")
    img = Image.open(SRC)
    print(f"  source: {img.size} mode={img.mode}")
    if img.mode == 'P':
        img = img.convert('RGBA')                  # palette -> RGBA (preserva trasparenza)
    elif img.mode not in ('RGB', 'RGBA'):
        img = img.convert('RGB')
    img = autocrop(img)
    print(f"  dopo autocrop: {img.size} aspect={img.size[0]/img.size[1]:.3f}")
    canvas = fit_into(img, LOGO_W, LOGO_H)
    pixels = [rgb888_to_rgb565_swapped(r, g, b) for (r, g, b) in canvas.convert('RGB').getdata()]
    write_header(OUT, "pang_logo", pixels)
    print("Done!")


if __name__ == '__main__':
    main()
