#!/usr/bin/env python3
"""
ROM converter for Space Invaders (Midway, 1978)
Converts invaders.zip MAME ROM set to C header files for Galagino

Space Invaders ROM set (invaders.zip):
  invaders.h  (2KB, 0x0000-0x07FF)
  invaders.g  (2KB, 0x0800-0x0FFF)
  invaders.f  (2KB, 0x1000-0x17FF)
  invaders.e  (2KB, 0x1800-0x1FFF)

Total: 8KB CPU ROM
No separate tile/sprite ROMs - uses bitmap framebuffer

Usage:
  python romconv_spaceinvaders.py

  Place invaders.zip in the romszip/ directory first.
"""

import zipfile
import os
import sys
from pathlib import Path

ROMSZIP_DIR = str((Path.cwd() / ".." / "ROMS" / "invaders.zip").resolve())
OUTPUT_DIR  = str((Path.cwd() / ".." / "machines" / "spaceinvaders").resolve())

# MAME ROM file names for "invaders" set
ROM_FILES = [
    ("invaders.h", 0x0800),  # 2KB at 0x0000
    ("invaders.g", 0x0800),  # 2KB at 0x0800
    ("invaders.f", 0x0800),  # 2KB at 0x1000
    ("invaders.e", 0x0800),  # 2KB at 0x1800
]

def write_header(filename, array_name, data, description=""):
    """Write a C header file with PROGMEM array"""
    filepath = os.path.join(OUTPUT_DIR, filename)
    with open(filepath, "w") as f:
        f.write(f"// {description}\n")
        f.write(f"// Auto-generated by romconv_spaceinvaders.py - DO NOT EDIT\n\n")
        f.write(f"#ifndef _{array_name}_h_\n")
        f.write(f"#define _{array_name}_h_\n\n")
        f.write(f"#include <pgmspace.h>\n\n")
        f.write(f"const unsigned char {array_name}[{len(data)}] PROGMEM = {{\n")

        for i in range(0, len(data), 16):
            chunk = data[i:i+16]
            hex_str = ", ".join(f"0x{b:02X}" for b in chunk)
            if i + 16 < len(data):
                hex_str += ","
            f.write(f"  {hex_str}\n")

        f.write(f"}};\n\n")
        f.write(f"#endif\n")

    print(f"  Written: {filepath} ({len(data)} bytes)")

def main():
    zip_path = ROMSZIP_DIR

    if not os.path.exists(zip_path):
        # Try alternative locations
        print(f"ERROR: Cannot find invaders.zip")
        print(f"  Looked in: {ROMSZIP_DIR}")
        print(f"  Place invaders.zip in the romszip/ directory")
        sys.exit(1)

    print(f"Reading ROM from: {zip_path}")

    # Read ROM files from ZIP
    rom_data = bytearray()

    with zipfile.ZipFile(zip_path, 'r') as zf:
        namelist = zf.namelist()
        print(f"  ZIP contents: {namelist}")

        for rom_name, expected_size in ROM_FILES:
            # Try exact name and case-insensitive match
            found = None
            for n in namelist:
                if n.lower() == rom_name.lower() or os.path.basename(n).lower() == rom_name.lower():
                    found = n
                    break

            if found is None:
                print(f"ERROR: ROM file '{rom_name}' not found in ZIP")
                print(f"  Available files: {namelist}")
                sys.exit(1)

            data = zf.read(found)
            if len(data) != expected_size:
                print(f"WARNING: {rom_name} is {len(data)} bytes, expected {expected_size}")

            rom_data.extend(data[:expected_size])
            print(f"  Loaded: {found} ({len(data)} bytes)")

    print(f"\nTotal ROM: {len(rom_data)} bytes")

    if len(rom_data) != 8192:
        print(f"ERROR: Expected 8192 bytes, got {len(rom_data)}")
        sys.exit(1)

    # Create output directory if needed
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    # Write ROM header
    write_header(
        "spaceinvaders_rom.h",
        "spaceinvaders_rom",
        rom_data,
        "Space Invaders CPU ROM (8KB: invaders.h + .g + .f + .e)"
    )

    print("\nDone! ROM converted successfully.")
    print("Space Invaders uses bitmap framebuffer - no tilemap/spritemap needed.")

if __name__ == "__main__":
    main()
