#!/usr/bin/env python3
"""
romconv_gigas2.py — converte gigasm2b.zip (Gigas Mark II bootleg, NO MC-8123)
in header C++ per il porting SPINNERINO.

Set: gigasm2b (Gigas Mark II bootleg, ROM gia' decifrate)
Driver MAME: misc/freekick.cpp ROM_START gigasm2b

Hardware IDENTICO a gigasb (Sega/Nihon System 1986):
  CPU      : Z80 @ 3.072 MHz singola
  Audio    : 4x SN76489A PSG
  Video    : 256x224 portrait ROT270
  GFX      : tile 8x8x3 plane (2048), sprite 16x16x3 plane (512)
  Palette  : 6 PROM 256B (IDENTICHE a gigasb, stessi CRC!)

Differenze rispetto a gigasb (vedi romconv_gigas.py):
  1) CPU 96KB ricostruita da 3 ROM 32KB invece di 1x32KB + 1x64KB:
       ROM_LOAD 8.rom 0x0c000 0x4000 + ROM_CONTINUE 0x00000 0x4000
       ROM_LOAD 7.rom 0x10000 0x4000 + ROM_CONTINUE 0x04000 0x4000
       ROM_LOAD 9.rom 0x14000 0x4000 + ROM_CONTINUE 0x08000 0x4000
  2) Sprite ROM_LOAD in ordine 1.rom, 3.rom, 2.rom (offset 0x0/0x4000/0x8000)
     -> p1 = 3.rom, p2 = 2.rom (in gigasb era p1=g-2, p2=g-3)
  3) Tile ROM_LOAD lineare 4/5/6.rom -> p0/p1/p2 (come gigasb)

Output (in machines/gigas2/):
  gigas2_rom_cpu.h          (96 KB Z80 ricostruito con dual-mapping)
  gigas2_gfx_tile_p0..p2.h  (3 x 16 KB tile plane)
  gigas2_gfx_spr_p0..p2.h   (3 x 16 KB sprite plane, ordine 1/3/2.rom)
  gigas2_palette.h          (512 colori RGB565 byte-swap, identica a gigas)

Tutta la logica della classe Gigas (gigas.cpp) e' riusabile come-e' su Gigas2
clonando la classe: stesso memory map, stesse PSG, stesso dual-mapping, stesso
blit_tile/blit_sprite (i p0/p1/p2 sono gia' nell'ordine offset-in-region).
"""
import zipfile, os, sys
from pathlib import Path

ZIP = str((Path.cwd() / ".." / "ROMS" / "gigasm2b.zip").resolve())
OUT  = str((Path.cwd() / ".." / "machines" / "gigas2").resolve())

def write_byte_array(path, var_name, data):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w') as f:
        f.write(f"// Auto-generated by romconv_gigas2.py\n")
        f.write(f"// {os.path.basename(path)}  size={len(data)} bytes\n")
        f.write(f"#include <stdint.h>\n\n")
        f.write(f"const uint8_t {var_name}[{len(data)}] PROGMEM = {{\n")
        for i in range(0, len(data), 16):
            chunk = data[i:i+16]
            f.write("  " + ", ".join(f"0x{b:02X}" for b in chunk) + ",\n")
        f.write("};\n")
    print(f"  wrote {path}  ({len(data)} bytes)")

def write_palette(path, var_name, palette_rgb565):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    n = len(palette_rgb565)
    with open(path, 'w') as f:
        f.write(f"// Auto-generated by romconv_gigas2.py\n")
        f.write(f"// {n} colors RGB565 byte-swap (ESP32 SPI BE)\n")
        f.write(f"const unsigned short {var_name}[{n}] PROGMEM = {{\n")
        for i in range(0, n, 8):
            chunk = palette_rgb565[i:i+8]
            f.write("  " + ", ".join(f"0x{p:04X}" for p in chunk) + ",\n")
        f.write("};\n")
    print(f"  wrote {path}  ({n} colors)")

def prom_4bit_to_8bit(nibble):
    """MAME palette_init_rgb_444_proms bit-weight: 0x0e, 0x1f, 0x43, 0x8f."""
    return (0x0e * ((nibble >> 0) & 1)
          | 0x1f * ((nibble >> 1) & 1)
          | 0x43 * ((nibble >> 2) & 1)
          | 0x8f * ((nibble >> 3) & 1))

def build_palette(prom_r, prom_g, prom_b):
    out = []
    for i in range(512):
        r = prom_4bit_to_8bit(prom_r[i] & 0x0F)
        g = prom_4bit_to_8bit(prom_g[i] & 0x0F)
        b = prom_4bit_to_8bit(prom_b[i] & 0x0F)
        rgb565 = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
        bs = ((rgb565 >> 8) & 0xFF) | ((rgb565 & 0xFF) << 8)
        out.append(bs)
    return out

def build_cpu_rom(r8, r7, r9):
    """ ROM region maincpu 0x18000 (96 KB) da 3x 32KB con ROM_CONTINUE:
        8.rom (32KB): primi 16KB -> 0x0C000, secondi 16KB -> 0x00000
        7.rom (32KB): primi 16KB -> 0x10000, secondi 16KB -> 0x04000
        9.rom (32KB): primi 16KB -> 0x14000, secondi 16KB -> 0x08000

        Layout finale (stesso pattern dual-mapping di gigasb):
          DATA section    : 0x00000-0x0BFFF (rdZ80, mreq normale)
          OPCODES section : 0x0C000-0x17FFF (opZ80, M1 fetch)
    """
    rom = bytearray(0x18000)
    rom[0x0C000:0x10000] = r8[0x0000:0x4000]
    rom[0x00000:0x04000] = r8[0x4000:0x8000]
    rom[0x10000:0x14000] = r7[0x0000:0x4000]
    rom[0x04000:0x08000] = r7[0x4000:0x8000]
    rom[0x14000:0x18000] = r9[0x0000:0x4000]
    rom[0x08000:0x0C000] = r9[0x4000:0x8000]
    return bytes(rom)

def main():
    if not os.path.exists(ZIP):
        print(f"!! ZIP non trovato: {ZIP}", file=sys.stderr); sys.exit(1)
    print(f"[romconv_gigas2] {ZIP}")
    zf = zipfile.ZipFile(ZIP)
    names = set(zf.namelist())

    needed = ["7.rom","8.rom","9.rom",
              "1.rom","2.rom","3.rom","4.rom","5.rom","6.rom",
              "1.pr","2.pr","3.pr","4.pr","5.pr","6.pr"]
    for n in needed:
        if n not in names:
            print(f"!! ROM mancante: {n}", file=sys.stderr); sys.exit(1)

    r7 = zf.read("7.rom"); r8 = zf.read("8.rom"); r9 = zf.read("9.rom")
    for nm, dt in (("7.rom",r7),("8.rom",r8),("9.rom",r9)):
        if len(dt) != 0x8000:
            print(f"!! size CPU ROM inattesa {nm}={len(dt)} (atteso 32768)", file=sys.stderr)
            sys.exit(1)

    cpu_rom = build_cpu_rom(r8, r7, r9)
    write_byte_array(os.path.join(OUT, "gigas2_rom_cpu.h"), "gigas2_rom_cpu", cpu_rom)

    # Tile plane 0..2 (4.rom, 5.rom, 6.rom) -- ordine lineare come gigasb
    write_byte_array(os.path.join(OUT, "gigas2_gfx_tile_p0.h"), "gigas2_gfx_tile_p0", zf.read("4.rom"))
    write_byte_array(os.path.join(OUT, "gigas2_gfx_tile_p1.h"), "gigas2_gfx_tile_p1", zf.read("5.rom"))
    write_byte_array(os.path.join(OUT, "gigas2_gfx_tile_p2.h"), "gigas2_gfx_tile_p2", zf.read("6.rom"))

    # Sprite plane 0..2 - ordine FISICO offset in region "sprites":
    #   0x0000 = 1.rom -> p0
    #   0x4000 = 3.rom -> p1  (!! 3.rom prima di 2.rom, diverso da gigasb)
    #   0x8000 = 2.rom -> p2
    # Replica la stessa "nome file -> ruolo plane" che gigas.cpp usa per gigasb.
    write_byte_array(os.path.join(OUT, "gigas2_gfx_spr_p0.h"), "gigas2_gfx_spr_p0", zf.read("1.rom"))
    write_byte_array(os.path.join(OUT, "gigas2_gfx_spr_p1.h"), "gigas2_gfx_spr_p1", zf.read("3.rom"))
    write_byte_array(os.path.join(OUT, "gigas2_gfx_spr_p2.h"), "gigas2_gfx_spr_p2", zf.read("2.rom"))

    # PROM palette 512 colori (file 1.pr/6.pr/5.pr/4.pr/2.pr/3.pr a 0x000..0x500
    # come gigasb -> stessa decodifica)
    prom_R = zf.read("1.pr") + zf.read("6.pr")
    prom_G = zf.read("5.pr") + zf.read("4.pr")
    prom_B = zf.read("2.pr") + zf.read("3.pr")
    palette = build_palette(prom_R, prom_G, prom_B)
    write_palette(os.path.join(OUT, "gigas2_palette.h"), "gigas2_palette", palette)

    print("Done!")

if __name__ == '__main__':
    main()
