#!/usr/bin/env python3
"""
romconv_arkanoid2.py — converte arknoid2.zip (set bootleg arknoid2b di MAME)
in header C++ per il porting SPINNERINO.

Set: arknoid2b (Arkanoid 2 - Revenge of Doh, Japan bootleg)
ROM da usare:
  boot.11c        64 KB  → maincpu Z80
  b08_13.3e       64 KB  → sub Z80 (audio + I/O)
  b08-01.13a    128 KB  → gfx1 plane 0
  b08-02.10a    128 KB  → gfx1 plane 1
  b08-03.7a     128 KB  → gfx1 plane 2
  b08-04.4a     128 KB  → gfx1 plane 3
  b08-08.15f      512 B  → palette PROM hi byte
  b08-07.16f      512 B  → palette PROM lo byte

Output (in SPINNERINO NEW P4/SPINNERINO/machines/arkanoid2/):
  arkanoid2_rom_main.h    const uint8_t arkanoid2_rom_main[0x10000]
  arkanoid2_rom_sub.h     const uint8_t arkanoid2_rom_sub[0x10000]
  arkanoid2_gfx_p0.h      const uint8_t arkanoid2_gfx_p0[0x20000]   plane 0
  arkanoid2_gfx_p1.h      const uint8_t arkanoid2_gfx_p1[0x20000]   plane 1
  arkanoid2_gfx_p2.h      const uint8_t arkanoid2_gfx_p2[0x20000]   plane 2
  arkanoid2_gfx_p3.h      const uint8_t arkanoid2_gfx_p3[0x20000]   plane 3
  arkanoid2_palette.h     const unsigned short arkanoid2_palette[256]  RGB565 byte-swap

Note layout tile:
  tnzs_charlayout (gfx_layout MAME):
    16x16 px, 4 bit-plane, 1024 tile per plane × 4 plane = 4096 tile totali
    Plane bits = { RGN_FRAC(3,4), RGN_FRAC(2,4), RGN_FRAC(1,4), RGN_FRAC(0,4) }
  Quindi: byte di plane 0 al base 0x00000, plane 1 al base 0x20000, ecc.
  Nel formato 4-ROM separate (come usate qui) ciascuna ROM e' un singolo plane.

Palette PROM (verificato MAME taito/tnzs.cpp / drv standard arkanoid):
  256 colori, 4 bit per canale RGB.
  - b08-08.15f (offset 0x000-0x0FF) = 4-bit hi (probabilmente R + G hi)
  - b08-07.16f (offset 0x100-0x1FF) = 4-bit lo (probabilmente G lo + B)
  Standard format per 256-color palette PROM Taito.
  Layout assunto: hi.lo[3:0]=R[3:0], lo.hi[3:0]=G[3:0], lo.lo[3:0]=B[3:0]
  Verificare al primo render; in caso di colori sbagliati riadattare in build_palette().

Stato porting al 2026-05-01:
  - CPU done: 2× Z80 main+sub, banking, shared RAM, sub-reset bit, MCU 8042
    HLE (mcu_r/mcu_w port MAME 1:1), interleave 8-slice + IRQ vblank a slice 6.
  - Sprite engine done: X1-001 draw_foreground + draw_background portati
    in arkanoid2.cpp (port MAME-fedele snapshot v4 da Paolo
    GALAGONE_4.3_P4_NEW_multi/arknoid2.cpp).
    Render formula sprite (2026-05-01):
      - FG: scratch_y = (242 - sy_raw) & 0xFF - 16   (MAME exact)
      - BG: yoffs = flip ? +1 : -1, flip applicato a sy/flipx/flipy
      - 1× blit (no 4× wrap), clip gestito da ark2_blit_tile_scratch.
  - Audio done: YM2203 PSG via path AY esteso + FM square approx + timer
    A/B con IRQ sub Z80 (BGM ritmo corretto, ma "limit BGM" issue noto).
  - Paddle done: uPD4701 emulato via ec11_dial_counter (free-running mod 256)
    del SPINNERINO SH + LEFT/RIGHT joy bridge. NO clamp (delta encoder).
    NB: NON usare ec11_paddle_x — e' clampato 0..255 dall'ISR e produce
    perdita di delta a saturazione (bug "paddle non va a sinistra in 2a vita",
    fix 2026-05-23). ARK2_EC11_STEP=2 (compensa lo step 6 del dial counter).
  - Buffer flip X1-001: tnzs_eof a slice 6 (vblank rising edge).
  - File: SPINNERINO NEW P4/SPINNERINO/machines/arkanoid2/arkanoid2.{h,cpp}
"""
import zipfile, os, sys
from pathlib import Path

ZIP = str((Path.cwd() / ".." / "ROMS" / "arknoid2.zip").resolve())
OUT  = str((Path.cwd() / ".." / "machines" / "arkanoid2").resolve())


ROMS = {
    "boot.11c":    ("arkanoid2_rom_main",  0x10000),
    "b08_13.3e":   ("arkanoid2_rom_sub",   0x10000),
    "b08-01.13a":  ("arkanoid2_gfx_p0",    0x20000),
    "b08-02.10a":  ("arkanoid2_gfx_p1",    0x20000),
    "b08-03.7a":   ("arkanoid2_gfx_p2",    0x20000),
    "b08-04.4a":   ("arkanoid2_gfx_p3",    0x20000),
}

def write_byte_array(path, var_name, data):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w') as f:
        f.write(f"// Auto-generated by romconv_arkanoid2.py\n")
        f.write(f"// Source ROM: {os.path.basename(path).replace('.h','.bin')}  size={len(data)} bytes\n")
        f.write(f"#include <stdint.h>\n\n")
        f.write(f"const uint8_t {var_name}[{len(data)}] PROGMEM = {{\n")
        for i in range(0, len(data), 16):
            chunk = data[i:i+16]
            f.write("  " + ", ".join(f"0x{b:02X}" for b in chunk) + ",\n")
        f.write("};\n")
    print(f"  wrote {path}  ({len(data)} bytes)")

def write_palette(path, var_name, palette_rgb565):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    n = len(palette_rgb565)
    with open(path, 'w') as f:
        f.write(f"// Auto-generated by romconv_arkanoid2.py\n")
        f.write(f"// {n} colors RGB565 byte-swap (ESP32 SPI BE), formato xRRRRRGGGGGBBBBB\n")
        f.write(f"const unsigned short {var_name}[{n}] PROGMEM = {{\n")
        for i in range(0, n, 8):
            chunk = palette_rgb565[i:i+8]
            f.write("  " + ", ".join(f"0x{p:04X}" for p in chunk) + ",\n")
        f.write("};\n")
    print(f"  wrote {path}  ({n} colors)")

def pal5bit(x):
    x &= 0x1F
    return (x << 3) | (x >> 2)   # estende 5-bit a 8-bit

def build_palette(prom_hi, prom_lo):
    """ Decoding palette TNZS/Arkanoid (verificato MAME taito/tnzs_video.cpp prompalette):
          col15 = (prom_hi[i] << 8) | prom_lo[i]    formato xRRRRR GGGGG BBBBB (15-bit)
        Output 512 colori RGB565 byte-swap.
    """
    n = min(len(prom_hi), len(prom_lo))   # tipicamente 512
    out = []
    for i in range(n):
        col = (prom_hi[i] << 8) | prom_lo[i]
        r = pal5bit(col >> 10)
        g = pal5bit(col >> 5)
        b = pal5bit(col >> 0)
        rgb565 = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
        bs = ((rgb565 >> 8) & 0xFF) | ((rgb565 & 0xFF) << 8)
        out.append(bs)
    return out

def decode_gfx_linear(p0, p1, p2, p3):
    """Pre-decode 4-plane 16x16 tile in formato linear 1 byte per pixel.
    Layout MAME tnzs_charlayout: per row y, byte_left=(y<8?y:y+8), byte_right=+8.
    Bit MSB-first (pixel 0 = bit 7).

    CRITICO: tnzs_charlayout in MAME ha planes[] in ordine DECRESCENTE:
      { RGN_FRAC(3,4), RGN_FRAC(2,4), RGN_FRAC(1,4), RGN_FRAC(0,4) }
    Quindi planes[0]=b08-04=MSB, planes[3]=b08-01=LSB.
    Nelle nostre variabili: p3 (b08-04) → bit 3 (MSB), p0 (b08-01) → bit 0 (LSB).

    Output: 4096 tile × 256 byte = 1 MB. Ogni byte = pixel 4-bit (0..15).
    Lettura runtime: 16 byte sequenziali per row → cache flash hit-rate elevato.
    """
    out = bytearray(4096 * 256)
    for tile in range(4096):
        base = tile * 32
        for y in range(16):
            byte_l = y + (8 if y >= 8 else 0)
            byte_r = byte_l + 8
            p0L, p1L, p2L, p3L = p0[base+byte_l], p1[base+byte_l], p2[base+byte_l], p3[base+byte_l]
            p0R, p1R, p2R, p3R = p0[base+byte_r], p1[base+byte_r], p2[base+byte_r], p3[base+byte_r]
            for i in range(8):
                s = 7 - i
                # tnzs_charlayout planes decrescente: p0=b08-01=LSB, p3=b08-04=MSB
                left  = ((p0L >> s) & 1) | (((p1L >> s) & 1) << 1) \
                      | (((p2L >> s) & 1) << 2) | (((p3L >> s) & 1) << 3)
                right = ((p0R >> s) & 1) | (((p1R >> s) & 1) << 1) \
                      | (((p2R >> s) & 1) << 2) | (((p3R >> s) & 1) << 3)
                out[tile * 256 + y * 16 + i]     = left
                out[tile * 256 + y * 16 + i + 8] = right
    return bytes(out)


def main():
    print(f"[romconv_arkanoid2] {ZIP}")
    if not os.path.exists(ZIP):
        print(f"!! ZIP non trovato: {ZIP}", file=sys.stderr)
        sys.exit(1)
    zf = zipfile.ZipFile(ZIP)
    names = set(zf.namelist())

    # ROM principali, audio e GFX
    plane_data = {}
    for romname, (var, expected_size) in ROMS.items():
        if romname not in names:
            print(f"!! ROM mancante nello zip: {romname}", file=sys.stderr)
            sys.exit(1)
        data = zf.read(romname)
        if len(data) != expected_size:
            print(f"!! ROM {romname}: size {len(data)} != atteso {expected_size}", file=sys.stderr)
            sys.exit(1)
        out_path = os.path.join(OUT, f"{var}.h")
        write_byte_array(out_path, var, data)
        plane_data[var] = data

    # === Pre-decoded GFX (NEW 2026-04-27) ===
    # Bottleneck identificato: 4 ROM scattered → cache miss flash.
    # Pre-decode offline → 1 array linear 1 MB, letture sequenziali.
    # Render time atteso: ~16 µs/tile vs ~64 µs (4x più veloce).
    print("[gfx decode] preprocessing 4096 tile × 16x16 = 1MB...")
    decoded = decode_gfx_linear(
        plane_data["arkanoid2_gfx_p0"],
        plane_data["arkanoid2_gfx_p1"],
        plane_data["arkanoid2_gfx_p2"],
        plane_data["arkanoid2_gfx_p3"],
    )
    write_byte_array(
        os.path.join(OUT, "arkanoid2_gfx_decoded.h"),
        "arkanoid2_gfx_decoded", decoded)

    # Palette PROM (512 colori, formato xRRRRRGGGGGBBBBB)
    if "b08-08.15f" in names and "b08-07.16f" in names:
        prom_hi = zf.read("b08-08.15f")
        prom_lo = zf.read("b08-07.16f")
        if len(prom_hi) == 512 and len(prom_lo) == 512:
            palette = build_palette(prom_hi, prom_lo)
            write_palette(os.path.join(OUT, "arkanoid2_palette.h"),
                          "arkanoid2_palette", palette)
        else:
            print(f"!! PROM size inattese: hi={len(prom_hi)} lo={len(prom_lo)}", file=sys.stderr)

    print("Done!")

if __name__ == '__main__':
    main()
