#!/usr/bin/env python3
"""
romconv_sbrkout.py — converte sbrkout.zip (Super Breakout, Atari 1978, rev 04)
in header C++ per il porting SPINNERINO P4.

Driver MAME: atari/sbrkout.cpp ROM_START sbrkout

Hardware:
  CPU      : M6502 @ 756 kHz (12.096 MHz XTAL / 16)
  Video    : 256x224 visible monocromatico (raster), tilemap 32x32 char 8x8
             + 3 "ball sprite" 3x3 px
  Audio    : DAC 1-bit (videoram[0x391] & scanline counter)
  Input    : paddle analogico + serve button + coin + start

Memory map 6502:
  0x0000-0x007F  zero page RAM (mirror +0x80/+0x100/+0x180/+0x200/+0x280/+0x300/+0x380)
  0x0400-0x07FF  Video RAM (tilemap 32x32)
  0x0800-0x083F  switch input read
  0x0C00-0x0C7F  output latch write
  0x0C80         watchdog reset
  0x0E00         IRQ ack
  0x2800-0x3FFF  ROM (6 KB)

ROM_START sbrkout (rev 04):
  ROM_REGION 0x4000 "maincpu"
    ROM_LOAD 033453.c1  0x2800  0x0800
    ROM_LOAD 033454.d1  0x3000  0x0800
    ROM_LOAD 033455.e1  0x3800  0x0800
  ROM_REGION 0x0400 "gfx1" (char ROM, 64 char 8x8 1bpp split-addressed)
    ROM_LOAD 033280.p4  0x0000  0x0200
    ROM_LOAD 033281.r4  0x0200  0x0200
  ROM_REGION 0x0020 "gfx2" (ball sprite 3x3 px)
    ROM_LOAD 033282.k6  0x0000  0x0020
  ROM_REGION 0x0120 "proms" (sync/timing, NON palette - mono fisso)
    ROM_LOAD 006400.m2  0x0000  0x0100
    ROM_LOAD 006401.e2  0x0100  0x0020

Output (in machines/sbrkout/):
  sbrkout_rom_cpu.h    16 KB region (ROM solo 0x2800-0x3FFF, resto 0xFF)
  sbrkout_gfx_char.h   1 KB char ROM (0x0000-0x03FF)
  sbrkout_gfx_ball.h   32 B ball sprite ROM

STATO: COMPLETO / FUNZIONANTE (2026-06-06). Questo script genera SOLO i .h ROM,
NON intaccati dai fix di emulazione; rigenerare solo se cambia sbrkout.zip.

Note ROM/gfx (2026-05-23):
  - ROM ball 033282.k6 ha SOLO byte 0..2 = 0xE0,0xE0,0xE0 (entry 0 = 3x3 pieno);
    byte 3..31 = 0x00 (entry 1 = vuoto, ball invisibile). Confermato anche da
    MiSTer Arcade-SuperBreakout (K6_PROM.vhd). In sbrkout.cpp force code=0
    + render come blob 6x6 GIALLO (3x3 troppo piccolo sul display).
  - char ROM: 64 char (charlayout MAME total=64). Il render usa code = byte&0x3F
    quando bit7 set (= byte mod 64, identico a MAME), char 0 (blank) se bit7 clear.
  - Orientation ROT270: y_orig = 223 - y_fb, x_orig = 255 - x_fb (pattern
    SpaceInvaders, entrambi gli assi MAME invertiti vs FB landscape).
  - HW rotation MAC=0x60 (empirico): user_y_display = 287 - arcade_y, cioe'
    arcade_y ALTI mappano a TOP user view.
  - Overlay PCB-accurate (NON sbrkout.lay default MAME): cornice top WHITE,
    mattoni BLU/ARANCIO/VERDE/GIALLO dal top user, paddle area WHITE.
    Muri laterali (mame_y < 8 || >= 216) sempre BIANCHI.
  - Paddle clamp 0..255 (paddle_pos cumulativo, NO wrap via dial_counter).

Bug risolti (lato emulazione, in sbrkout.cpp/.h — NON in questo converter):
  - 2026-05-24 "palla invisibile": vram[$380..$3FF] e' ALIAS di zero page
    (bank1 MAME punta a videoram[0x380]); rd6502/wr6502 ora redirigono a ZP,
    ball coords lette da memory[$10..$1F].
  - 2026-06-06 "paddle invisibile a centro/destra sotto carico": irq6502() di
    fake6502 NON controlla il flag I e veniva chiamato incondizionato → IRQ
    forzato anche durante SEI (sezione critica disegno paddle). Fix: IRQ
    level-held che rispetta I + ack $0E00; + stepping exec6502(48) cycle-accurate.
"""
import zipfile, os, sys
from pathlib import Path


ZIP = str((Path.cwd() / ".." / "ROMS" / "sbrkout.zip").resolve())
OUT  = str((Path.cwd() / ".." / "machines" / "sbrkout").resolve())

def write_byte_array(path, var_name, data):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w') as f:
        f.write(f"// Auto-generated by romconv_sbrkout.py\n")
        f.write(f"// {os.path.basename(path)}  size={len(data)} bytes\n")
        f.write(f"#include <stdint.h>\n\n")
        f.write(f"const uint8_t {var_name}[{len(data)}] PROGMEM = {{\n")
        for i in range(0, len(data), 16):
            chunk = data[i:i+16]
            f.write("  " + ", ".join(f"0x{b:02X}" for b in chunk) + ",\n")
        f.write("};\n")
    print(f"  wrote {path}  ({len(data)} bytes)")


def main():
    if not os.path.exists(ZIP):
        print(f"!! ZIP non trovato: {ZIP}", file=sys.stderr); sys.exit(1)
    print(f"[romconv_sbrkout] {ZIP}")
    zf = zipfile.ZipFile(ZIP)
    names = set(zf.namelist())

    needed = ["033453.c1", "033454.d1", "033455.e1",
              "033280.p4", "033281.r4",
              "033282.k6"]
    for n in needed:
        if n not in names:
            print(f"!! ROM mancante: {n}", file=sys.stderr); sys.exit(1)

    # ---- CPU ROM region 16 KB (0xFF fill, ROM a 0x2800-0x3FFF) ----
    rom = bytearray([0xFF] * 0x4000)
    rom[0x2800:0x3000] = zf.read("033453.c1")
    rom[0x3000:0x3800] = zf.read("033454.d1")
    rom[0x3800:0x4000] = zf.read("033455.e1")
    write_byte_array(os.path.join(OUT, "sbrkout_rom_cpu.h"),
                     "sbrkout_rom_cpu", bytes(rom))

    # ---- GFX1 char ROM (1 KB = 2x512B concatenate) ----
    char_rom = zf.read("033280.p4") + zf.read("033281.r4")
    write_byte_array(os.path.join(OUT, "sbrkout_gfx_char.h"),
                     "sbrkout_gfx_char", char_rom)

    # ---- GFX2 ball sprite ROM (32 B) ----
    ball_rom = zf.read("033282.k6")
    write_byte_array(os.path.join(OUT, "sbrkout_gfx_ball.h"),
                     "sbrkout_gfx_ball", ball_rom)

    # PROMS sync/timing NON inclusi (palette monocromatica fissa, non servono)
    print("Done!")


if __name__ == '__main__':
    main()
