#!/usr/bin/env python3
"""
romconv_goindol.py — converte goindol.zip (Goindol, SunA Electronics 1987)
in header C++ per il porting SPINNERINO WIFI.

Set: goindol (World).  Driver MAME: src/mame/suna/goindol.cpp

================================================================================
HARDWARE (da goindol.cpp verbatim)
================================================================================
  CPU main : Z80 @ 12 MHz/2 (6 MHz)
  CPU sound: Z80 @ 12 MHz/2
  Audio    : YM2203 @ 12 MHz/8  (FM + 3x SSG)  -> path stile GnG/Boblbobl (fm.c)
  Display  : 256x224, ROT90 (verticale)
  Controllo: dial/spinner (0xC820) + joystick + 2 button + START + COIN
  Protezione: blocco epoxy presso lo Z80 main (handler R/W a
              0xF422 / 0xFC44 / 0xFC66 / 0xFCB0 / 0xFD99) -> da gestire nel .cpp

ROM_START(goindol):
  maincpu  (region 0x20000):
    r1w  0x00000  0x8000   code fisso  0x0000-0x7FFF
    r2   0x10000  0x8000   banked (banchi 0,1)
    r3   0x18000  0x8000   banked (banchi 2,3)
  audiocpu (region 0x10000):
    r10  0x00000  0x8000   code sound Z80 0x0000-0x7FFF
  fg_chars (region 0x18000 = 96 KB, 3 plane RGN_FRAC):
    r4   0x00000  0x8000   plane @ RGN_FRAC(0,3)
    r5   0x08000  0x8000   plane @ RGN_FRAC(1,3)
    r6   0x10000  0x8000   plane @ RGN_FRAC(2,3)
  bg_chars (region 0x18000 = 96 KB, 3 plane RGN_FRAC):
    r7   0x00000  0x8000
    r8   0x08000  0x8000
    r9   0x10000  0x8000
  proms (region 0x300):
    am27s21.pr1  0x000  0x100   R (4-bit)
    am27s21.pr2  0x100  0x100   G (4-bit)
    am27s21.pr3  0x200  0x100   B (4-bit)

================================================================================
GFX LAYOUT (charlayout, identico per fg e bg)
================================================================================
  8x8 px, 3 plane, RGN_FRAC(1,3) tiles per regione = 32768/8 = 4096 tile.
  planeoffset = { RGN_FRAC(0,3), RGN_FRAC(1,3), RGN_FRAC(2,3) }
    -> plane[0] = primo file (r4/r7), plane[1] = secondo, plane[2] = terzo.
  xoffset = {0..7} (MSB-first: bit 7 = pixel sinistro), yoffset = {0*8..7*8}.
  8 byte per tile per plane.

  NB ORDINE BIT-PLANE: MAME mette planeoffset[0] sul bit piu' significativo del
  valore pixel. In questo codebase pero' il gemello SunA "gigas" (stesso macro
  charlayout) e' risultato corretto on-device con plane[0]=LSB
  (pix = (p2<<2)|(p1<<1)|p0). Il converter scrive i 3 file in ORDINE-FILE
  (p0=r4, p1=r5, p2=r6); l'interpretazione LSB/MSB sta nel .cpp blit_tile e
  va verificata/regolata on-device in fase 2.

================================================================================
SPRITE (draw_sprites) — NESSUNA ROM SPRITE DEDICATA
================================================================================
  Gli sprite riusano i tile 8x8 di fg_chars o bg_chars (gfxbank 0/1):
    sx = spr[offs+0]
    sy = 240 - spr[offs+1]
    visibile se (spr[offs+1] >> 3) && sx < 248
    tile = (spr[offs+3] | ((spr[offs+2] & 7) << 8)) * 2
    palette = spr[offs+2] >> 3
    disegna tile @ (sx,sy) e tile+1 @ (sx, sy+8)  -> sprite 8x16
  Quindi il converter NON genera header sprite separati.

================================================================================
PALETTE (palette_device::RGB_444_PROMS, 256 colori)
================================================================================
  R = pal4bit(pr1[i] & 0x0F) ; G = pal4bit(pr2[i]) ; B = pal4bit(pr3[i])
  pal4bit(n) = (n & 0x0F) * 0x11   (0xF -> 0xFF)
  -> RGB565 byte-swap (ESP32 SPI big-endian), come negli altri header.

OUTPUT (in machines/goindol/):
  goindol_rom_fixed.h    (32 KB, r1w -> 0x0000-0x7FFF)
  goindol_rom_bank.h     (64 KB, r2+r3 -> 4 banchi da 16 KB selezionati da 0xC810)
  goindol_rom_audio.h    (32 KB, r10 sound Z80)
  goindol_gfx_fg_p0..p2.h (3 x 32 KB, tile FG)
  goindol_gfx_bg_p0..p2.h (3 x 32 KB, tile BG)
  goindol_palette.h      (256 colori RGB565 byte-swap)
"""
import zipfile, os, sys
from pathlib import Path

# Path portabili (come gli altri converter di SPINNERINO): ROM in ../ROMS/,
# output in ../machines/goindol/. Eseguire da dentro ROM_CONVERTER/.
ZIP = str((Path.cwd() / ".." / "ROMS" / "goindol.zip").resolve())
OUT = str((Path.cwd() / ".." / "machines" / "goindol").resolve())


def write_byte_array(path, var_name, data):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w') as f:
        f.write("// Auto-generated by romconv_goindol.py\n")
        f.write(f"// {os.path.basename(path)}  size={len(data)} bytes\n")
        f.write("#include <stdint.h>\n\n")
        f.write(f"const uint8_t {var_name}[{len(data)}] PROGMEM = {{\n")
        for i in range(0, len(data), 16):
            chunk = data[i:i+16]
            f.write("  " + ", ".join(f"0x{b:02X}" for b in chunk) + ",\n")
        f.write("};\n")
    print(f"  wrote {path}  ({len(data)} bytes)")


def write_palette(path, var_name, palette_rgb565):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    n = len(palette_rgb565)
    with open(path, 'w') as f:
        f.write("// Auto-generated by romconv_goindol.py\n")
        f.write(f"// {n} colors RGB565 byte-swap (ESP32 SPI BE)\n")
        f.write(f"const unsigned short {var_name}[{n}] PROGMEM = {{\n")
        for i in range(0, n, 8):
            chunk = palette_rgb565[i:i+8]
            f.write("  " + ", ".join(f"0x{p:04X}" for p in chunk) + ",\n")
        f.write("};\n")
    print(f"  wrote {path}  ({n} colors)")


def pal4bit(nibble):
    """RGB_444 expand: nibble 0..15 -> 8 bit (n*0x11)."""
    n = nibble & 0x0F
    return (n << 4) | n


def build_palette(prom_r, prom_g, prom_b):
    """Ognuna 256 byte. Ritorna 256 colori RGB565 byte-swap."""
    out = []
    for i in range(256):
        r = pal4bit(prom_r[i])
        g = pal4bit(prom_g[i])
        b = pal4bit(prom_b[i])
        rgb565 = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
        bs = ((rgb565 >> 8) & 0xFF) | ((rgb565 & 0xFF) << 8)
        out.append(bs)
    return out


def need(zf, name):
    if name not in zf.namelist():
        print(f"!! ROM mancante nello zip: {name}", file=sys.stderr)
        sys.exit(1)
    return zf.read(name)


def main():
    if not os.path.exists(ZIP):
        print(f"!! ZIP non trovato: {ZIP}", file=sys.stderr)
        sys.exit(1)
    print(f"[romconv_goindol] {ZIP}")
    zf = zipfile.ZipFile(ZIP)

    # --- CPU main ---
    r1w = need(zf, "r1w")   # 32 KB code fisso
    r2  = need(zf, "r2")    # 32 KB banked
    r3  = need(zf, "r3")    # 32 KB banked
    for nm, d in (("r1w", r1w), ("r2", r2), ("r3", r3)):
        if len(d) != 0x8000:
            print(f"!! size inattesa {nm}={len(d)} (atteso 0x8000)", file=sys.stderr)
            sys.exit(1)

    # ── Patch di protezione (da MAME suna/goindol.cpp init_goindol) ──
    # Il boot di Goindol esegue una serie di verifiche MCU/protezione: se non
    # passano mostra "ROM 1 check" / "ROM 9 ERROR" e si blocca. MAME NON supera
    # il test, lo BYPASSA scrivendo NOP(0x18)/RET(0xC9)/0x00 nei punti di
    # controllo. Tutti gli offset sono nella ROM fissa r1w (0x0000-0x7FFF).
    # Replichiamo gli stessi patch attivi di MAME (le righe commentate nel
    # driver sono l'approccio alternativo via injection RAM, che noi gia'
    # implementiamo come handler 0xFC44/FC66/FCB0/FD99 nel .cpp).
    r1w = bytearray(r1w)
    GOINDOL_PROT_PATCHES = {
        0x18E9: 0x18,  # ROM 1 check  -> JR
        0x1964: 0x00,  # ROM 9 error (MCU?)
        0x1965: 0x00,  #
        0x1966: 0x00,  #
        0x063F: 0x18,  # ->fc55
        0x0B30: 0x00,  # verify code at 0601-064b
        0x1BDF: 0x18,  # ->fc49
        0x04A7: 0xC9,  # RET
        0x0831: 0xC9,  # RET
        0x3365: 0x00,  # verify code at 081d-0876
        0x0C13: 0xC9,  # RET
        0x134E: 0xC9,  # RET
        0x333D: 0xC9,  # RET
    }
    for off, val in GOINDOL_PROT_PATCHES.items():
        r1w[off] = val
    print(f"  applied {len(GOINDOL_PROT_PATCHES)} init_goindol protection patches to r1w")

    write_byte_array(os.path.join(OUT, "goindol_rom_fixed.h"), "goindol_rom_fixed", r1w)
    # banked: r2 (banchi 0,1) seguito da r3 (banchi 2,3) = 64 KB contigui.
    # Bank N (N=0..3) = bank[N*0x4000 : N*0x4000+0x4000], finestra Z80 0x8000-0xBFFF.
    write_byte_array(os.path.join(OUT, "goindol_rom_bank.h"), "goindol_rom_bank", r2 + r3)

    # --- CPU sound ---
    r10 = need(zf, "r10")
    write_byte_array(os.path.join(OUT, "goindol_rom_audio.h"), "goindol_rom_audio", r10)

    # --- GFX FG (r4,r5,r6) ---
    write_byte_array(os.path.join(OUT, "goindol_gfx_fg_p0.h"), "goindol_gfx_fg_p0", need(zf, "r4"))
    write_byte_array(os.path.join(OUT, "goindol_gfx_fg_p1.h"), "goindol_gfx_fg_p1", need(zf, "r5"))
    write_byte_array(os.path.join(OUT, "goindol_gfx_fg_p2.h"), "goindol_gfx_fg_p2", need(zf, "r6"))

    # --- GFX BG (r7,r8,r9) ---
    write_byte_array(os.path.join(OUT, "goindol_gfx_bg_p0.h"), "goindol_gfx_bg_p0", need(zf, "r7"))
    write_byte_array(os.path.join(OUT, "goindol_gfx_bg_p1.h"), "goindol_gfx_bg_p1", need(zf, "r8"))
    write_byte_array(os.path.join(OUT, "goindol_gfx_bg_p2.h"), "goindol_gfx_bg_p2", need(zf, "r9"))

    # --- Palette ---
    pr1 = need(zf, "am27s21.pr1")   # R
    pr2 = need(zf, "am27s21.pr2")   # G
    pr3 = need(zf, "am27s21.pr3")   # B
    for nm, d in (("pr1", pr1), ("pr2", pr2), ("pr3", pr3)):
        if len(d) != 0x100:
            print(f"!! size PROM inattesa {nm}={len(d)} (atteso 0x100)", file=sys.stderr)
            sys.exit(1)
    palette = build_palette(pr1, pr2, pr3)
    write_palette(os.path.join(OUT, "goindol_palette.h"), "goindol_palette", palette)

    print("Done!")


if __name__ == '__main__':
    main()
