#!/usr/bin/env python3
# romconv_phoenix.py
# Converte le ROM Phoenix (set "phoenix", Amstar/Centuri 1980) negli header
# .h usati dal porting SPINNERINO.

import os
import sys
import zipfile
import tempfile
from pathlib import Path


def read(rom_dir, name):
    path = os.path.join(rom_dir, name)
    if not os.path.isfile(path):
        candidates = [n for n in os.listdir(rom_dir) if n.startswith(name.split("-")[0])]
        if candidates:
            path = os.path.join(rom_dir, candidates[0])
            print(f"[FALLBACK] {name} -> {os.path.basename(path)}")
        else:
            raise FileNotFoundError(f"{name} non trovato in {rom_dir}")
    with open(path, "rb") as f:
        return f.read()


def emit_byte_array(name, data, comment=""):
    lines = [
        "// Auto-generated by romconv_phoenix.py - DO NOT EDIT",
        f"// {comment}" if comment else "",
        f"const unsigned char {name}[{len(data)}] PROGMEM = {{",
    ]
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        lines.append(" " + ", ".join(f"0x{b:02X}" for b in chunk) +
                     ("," if i + 16 < len(data) else ""))
    lines.append("};")
    lines.append("")
    return "\n".join(l for l in lines if l is not None)


def emit_word_array(name, words, comment=""):
    lines = [
        "// Auto-generated by romconv_phoenix.py - DO NOT EDIT",
        f"// {comment}" if comment else "",
        f"const unsigned short {name}[{len(words)}] PROGMEM = {{",
    ]
    for i in range(0, len(words), 12):
        chunk = words[i:i + 12]
        lines.append(" " + ", ".join(f"0x{w:04X}" for w in chunk) +
                     ("," if i + 12 < len(words) else ""))
    lines.append("};")
    lines.append("")
    return "\n".join(l for l in lines if l is not None)


def to_rgb565_swap(r, g, b):
    rgb565 = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
    return ((rgb565 >> 8) | (rgb565 << 8)) & 0xFFFF


def decode_palette(prom_lo, prom_hi):
    LEVELS = [0, 0, 202, 255]
    palette = []

    for i in range(256):
        b6 = (i >> 6) & 1
        b5 = (i >> 5) & 1
        b1 = (i >> 1) & 1
        b0 = (i >> 0) & 1
        b4 = (i >> 4) & 1
        b3 = (i >> 3) & 1
        b2 = (i >> 2) & 1

        col = (b6 << 6) | (b5 << 5) | (b1 << 4) | (b0 << 3) | (b4 << 2) | (b3 << 1) | b2

        lo = prom_lo[col]
        hi = prom_hi[col]

        r_bits = ((lo >> 0) & 1) | (((hi >> 0) & 1) << 1)
        g_bits = ((lo >> 2) & 1) | (((hi >> 2) & 1) << 1)
        b_bits = ((lo >> 1) & 1) | (((hi >> 1) & 1) << 1)

        r = LEVELS[r_bits]
        g = LEVELS[g_bits]
        b = LEVELS[b_bits]

        palette.append(to_rgb565_swap(r, g, b))

    return palette


def main():
    zip_path = (Path.cwd() / ".." / "ROMS" / "phoenix.zip").resolve()
    out_dir = (Path.cwd() / ".." / "machines" / "phoenix").resolve()

    os.makedirs(out_dir, exist_ok=True)

    if not zip_path.exists():
        print(f"[ERRORE] ZIP non trovato: {zip_path}", file=sys.stderr)
        sys.exit(1)

    with tempfile.TemporaryDirectory(prefix="phoenix_") as temp_dir:
        with zipfile.ZipFile(zip_path, "r") as zf:
            zf.extractall(temp_dir)

        rom_dir = temp_dir

        cpu_rom = bytearray(16 * 1024)
        pg_files = [
            ("ic45-pg1.1a", 0x0000),
            ("ic46-pg2.2a", 0x0800),
            ("ic47-pg3.3a", 0x1000),
            ("ic48-pg4.4a", 0x1800),
            ("ic49-pg5.5a", 0x2000),
            ("ic50-pg6.6a", 0x2800),
            ("ic51-pg7.7a", 0x3000),
            ("ic52-pg8.8a", 0x3800),
        ]

        for name, off in pg_files:
            d = read(rom_dir, name)
            if len(d) != 0x800:
                raise ValueError(f"{name} dimensione errata: {len(d)} (atteso 2048)")
            cpu_rom[off:off + 0x800] = d

        with open(os.path.join(out_dir, "phoenix_rom.h"), "w", encoding="utf-8", newline="\n") as f:
            f.write(emit_byte_array("phoenix_rom", cpu_rom, "Z80 CPU ROM 16 KB (ic45..ic52)"))
        print(f"[OK] phoenix_rom.h ({len(cpu_rom)} byte)")

        bg_p0 = read(rom_dir, "ic23-cg1.3d")
        bg_p1 = read(rom_dir, "ic24-cg2.4d")
        bg_data = bg_p0 + bg_p1

        with open(os.path.join(out_dir, "phoenix_bgtiles.h"), "w", encoding="utf-8", newline="\n") as f:
            f.write(emit_byte_array("phoenix_bgtiles", bg_data,
                                    "BG tiles 4 KB (256 char × 8x8 × 2bpp), plane0 + plane1"))
        print(f"[OK] phoenix_bgtiles.h ({len(bg_data)} byte)")

        fg_p0 = read(rom_dir, "ic39-cg3.3b")
        fg_p1 = read(rom_dir, "ic40-cg4.4b")
        fg_data = fg_p0 + fg_p1

        with open(os.path.join(out_dir, "phoenix_fgtiles.h"), "w", encoding="utf-8", newline="\n") as f:
            f.write(emit_byte_array("phoenix_fgtiles", fg_data,
                                    "FG tiles 4 KB (256 char × 8x8 × 2bpp), plane0 + plane1"))
        print(f"[OK] phoenix_fgtiles.h ({len(fg_data)} byte)")

        prom_lo = read(rom_dir, "mmi6301.ic40")
        prom_hi = read(rom_dir, "mmi6301.ic41")
        if len(prom_lo) != 256 or len(prom_hi) != 256:
            raise ValueError("PROM palette dimensione non 256 byte")

        palette_rgb = decode_palette(prom_lo, prom_hi)

        with open(os.path.join(out_dir, "phoenix_palette.h"), "w", encoding="utf-8", newline="\n") as f:
            f.write(emit_word_array("phoenix_palette", palette_rgb,
                                    "256 colori RGB565 byte-swapped (mmi6301 ic40 + ic41)"))
        print(f"[OK] phoenix_palette.h (256 colori)")

        dipsw = """\
#ifndef PHOENIX_DIPSWITCHES_H
#define PHOENIX_DIPSWITCHES_H
// MAME default DSW0:
// bit 0-1 = lives (0=3, 1=4, 2=5, 3=6) -> default 0x00 (3 lives)
// bit 2-3 = bonus (0=3K/30K, 1=4K/40K, ...) -> default 0x00
// bit 4 = coinage (0=2c1c, 1=1c1c) -> default 0x10
// bit 5,6 = unknown -> 0
// bit 7 = VBLANK (gestito dinamicamente nel rdZ80)
#define PHOENIX_DSW0 0x10
#endif
"""
        with open(os.path.join(out_dir, "phoenix_dipswitches.h"), "w", encoding="utf-8", newline="\n") as f:
            f.write(dipsw)
        print("[OK] phoenix_dipswitches.h")

    print("\n[DONE] tutti i file generati in", out_dir)


if __name__ == "__main__":
    main()