#!/usr/bin/env python3
"""
romconv_bombbee.py — converte bombbee.zip (Bomb Bee, Namco 1979) in header C++
per il porting SPINNERINO P4.

Driver MAME: namco/warpwarp.cpp  (set "bombbee", hardware "color games" Namco 8080)

Hardware:
  CPU      : Intel 8080 @ 2.048 MHz (MASTER_CLOCK 18.432/9) — emulato su core Z80
  Video    : raster 272x224, ROT90, tilemap 8x8 34x28 (scan 32x32->34x28)
             + "ball" hardware 4x4. Colore generato da rete resistori
             (warpwarp_palette, 2*256+1 pen). NESSUNA PROM colore.
  Audio    : WARPWARP_SOUND custom (NE556), 2 canali freq+shape
  Input    : paddle analogico (VOLIN1, range 0x14..0xAC REVERSE) + serve (IN0 bit4)

Memory map 8080 (bombbee_map):
  0x0000-0x1FFF  ROM programma (8 KB)
  0x2000-0x23FF  RAM lavoro (1 KB)
  0x4000-0x47FF  Video RAM (2 KB): 0x4000-0x43FF tile code, 0x4400-0x47FF colore
  0x4800-0x4FFF  ROM grafica char (2 KB, mappata in spazio CPU)
  0x6000-0x600F  R: switch (IN0 bit-serial)   W: ball_h/ball_v/sound0/watchdog
  0x6010-0x601F  R: paddle (VOLIN1)            W: music ch1
  0x6020-0x602F  R: DSW1 (bit-serial)          W: music ch2
  0x6030-0x6037  W: latch LS259 (bit6=ball_on, bit7=flip, lamps/coin/counter)

ROM set bombbee.zip (TorrentZip):
  bombbee.1k  (8 KB)  programma 8080  -> region 0x0000-0x1FFF
  bombbee.4c  (2 KB)  char gfx 8x8x1  -> region "gfx1"

Output (in machines/bombbee/):
  bombbee_rom.h   8 KB  -> const unsigned char bombbee_rom[8192]
  bombbee_gfx.h   2 KB  -> const unsigned char bombbee_gfx[2048]

NB: lo script genera SOLO i .h ROM (non intaccati dai fix di emulazione).
Rigenerare solo se cambia bombbee.zip.
"""

import zipfile, os, sys
from pathlib import Path

ZIP = str((Path.cwd() / ".." / "ROMS" / "bombbee.zip").resolve())
OUT = str((Path.cwd() / ".." / "machines" / "bombbee").resolve())

# Nome canonico -> (dimensione attesa). Match case-insensitive; in fallback
# si seleziona per dimensione (8 KB = programma, 2 KB = gfx).
PRG_NAMES = ["bombbee.1k", "bombbee.2k", "bombbee.1l"]
GFX_NAMES = ["bombbee.4c"]


def write_header(filename, array_name, data, description=""):
    os.makedirs(OUT, exist_ok=True)
    path = os.path.join(OUT, filename)
    with open(path, "w") as f:
        f.write(f"// {description}\n")
        f.write(f"// Auto-generated by romconv_bombbee.py - DO NOT EDIT\n\n")
        f.write(f"#ifndef _{array_name}_h_\n")
        f.write(f"#define _{array_name}_h_\n\n")
        f.write(f"#include <pgmspace.h>\n\n")
        f.write(f"const unsigned char {array_name}[{len(data)}] PROGMEM = {{\n")
        for i in range(0, len(data), 16):
            chunk = data[i:i+16]
            hex_str = ", ".join(f"0x{b:02X}" for b in chunk)
            if i + 16 < len(data):
                hex_str += ","
            f.write(f"  {hex_str}\n")
        f.write(f"}};\n\n#endif\n")
    print(f"  wrote {path}  ({len(data)} bytes)")


def find_rom(zf, names, want_size):
    """Trova una ROM per nome (case-insensitive) o, in fallback, per dimensione."""
    members = zf.namelist()
    for want in names:
        for m in members:
            if os.path.basename(m).lower() == want.lower():
                return m
    # fallback: primo file con la dimensione attesa
    for m in members:
        try:
            if zf.getinfo(m).file_size == want_size:
                return m
        except KeyError:
            pass
    return None


def main():
    if not os.path.exists(ZIP):
        print(f"!! ZIP non trovato: {ZIP}", file=sys.stderr)
        print(f"   Metti bombbee.zip in ROMS/", file=sys.stderr)
        sys.exit(1)
    print(f"[romconv_bombbee] {ZIP}")
    zf = zipfile.ZipFile(ZIP)
    print(f"  contenuto: {zf.namelist()}")

    prg = find_rom(zf, PRG_NAMES, 8192)
    gfx = find_rom(zf, GFX_NAMES, 2048)
    if prg is None:
        print("!! ROM programma 8 KB non trovata", file=sys.stderr); sys.exit(1)
    if gfx is None:
        print("!! ROM gfx 2 KB non trovata", file=sys.stderr); sys.exit(1)

    prg_data = zf.read(prg)
    gfx_data = zf.read(gfx)
    print(f"  programma: {prg} ({len(prg_data)} B)")
    print(f"  gfx:       {gfx} ({len(gfx_data)} B)")

    if len(prg_data) != 8192:
        print(f"WARNING: programma {len(prg_data)} B, atteso 8192", file=sys.stderr)
    if len(gfx_data) != 2048:
        print(f"WARNING: gfx {len(gfx_data)} B, atteso 2048", file=sys.stderr)

    write_header("bombbee_rom.h", "bombbee_rom", prg_data[:8192],
                 "Bomb Bee programma 8080 (8 KB)")
    write_header("bombbee_gfx.h", "bombbee_gfx", gfx_data[:2048],
                 "Bomb Bee char gfx 8x8x1 (2 KB, 256 char)")
    print("Done!")


if __name__ == "__main__":
    main()
