#!/usr/bin/env python3
"""
romconv_arkangc.py — ROM converter for Arkanoid bootleg "arkangc" (Game Corp)
ROM set richiesto: arkangc.zip (MAME, NO MCU 68705)

Hardware (MAME taito/arkanoid.cpp, verificato 2026-04-26):
  CPU:   Z80 @ 6 MHz (12 MHz XTAL / 2)
  Sound: 1x AY-3-8910 (NON YM2149 nel bootleg arkangc)
         Pin clock = 12 MHz XTAL / 4 = 3 MHz (MAME ay8910.cpp:1342:
         set_sample_rate(clock/8) per AY-3-8910 standard).
         Tone freq = 3 MHz / (8 * 2 * TP) = 187500 / TP Hz
  Video: 256x224 ROT270, 32x32 tilemap (di cui 32x28 visibili)
  GFX:   4096 char 8x8 3bpp (planar separato in 3 ROM da 32KB)
         Sprite 16x16 = 4 char 8x8 disposti 2x2, stessa GFX
  Palette: 512 colori RGB444 da 3 PROM (a75-07/08/09.bpr)

ROM set arkangc:
  arkgc.1     32KB  CPU ROM bank 0  (0x0000-0x7FFF)
  arkgc.2     32KB  CPU ROM bank 1  (banked, raramente usato in bootleg)
  a75-03.rom  32KB  GFX plane 0 (LSB)
  a75-04.rom  32KB  GFX plane 1
  a75-05.rom  32KB  GFX plane 2 (MSB)
  a75-07.bpr   512  PROM red    (RGB_444_PROMS, 4-bit intensita')
  a75-08.bpr   512  PROM green
  a75-09.bpr   512  PROM blue

Output (ARKANOID SH/arkanoid/machines/arkanoid/):
  arkanoid_rom_cpu.h    Z80 ROM 64KB
  arkanoid_tilemap.h    4096 tile 8x8 3bpp, packed long[8] (4 bit per pixel)
  arkanoid_spritemap.h  alias struttura per assemblare 16x16 (4 char 2x2)
  arkanoid_palette.h    512 colori RGB565 byte-swap (BE) per ESP32 SPI
  arkanoid_logo.h       logo placeholder (1x1, da rigenerare con script logo)
"""
import sys, os, zipfile
from pathlib import Path

# ──────────────────────────────────────────────────────────────────────────
# I/O helpers
# ──────────────────────────────────────────────────────────────────────────
def read_rom(zf, name, expected_size=None):
    data = zf.read(name)
    if expected_size and len(data) != expected_size:
        print(f"  WARN: {name} = {len(data)}B, expected {expected_size}B")
    return data

def write_header_bytes(path, var_name, data, dtype="unsigned char", note=""):
    with open(path, 'w') as f:
        f.write(f"// Auto-generated by romconv_arkangc.py {note}\n")
        f.write(f"const unsigned int {var_name}_size = {len(data)};\n")
        f.write(f"const {dtype} {var_name}[] PROGMEM = {{\n")
        for i in range(0, len(data), 16):
            chunk = data[i:i+16]
            f.write("  " + ", ".join(f"0x{b:02X}" for b in chunk) + ",\n")
        f.write("};\n")
    print(f"  wrote {path}  ({len(data)} bytes)")

def write_header_words(path, var_name, words, dtype="unsigned short"):
    with open(path, 'w') as f:
        f.write(f"// Auto-generated by romconv_arkangc.py\n")
        f.write(f"const unsigned int {var_name}_count = {len(words)};\n")
        f.write(f"const {dtype} {var_name}[] PROGMEM = {{\n")
        for i in range(0, len(words), 8):
            chunk = words[i:i+8]
            f.write("  " + ", ".join(f"0x{w:04X}" for w in chunk) + ",\n")
        f.write("};\n")
    print(f"  wrote {path}  ({len(words)} words)")

def write_header_longs(path, var_name, longs):
    with open(path, 'w') as f:
        f.write(f"// Auto-generated by romconv_arkangc.py\n")
        f.write(f"const unsigned int {var_name}_count = {len(longs)};\n")
        f.write(f"const unsigned long {var_name}[] PROGMEM = {{\n")
        for i in range(0, len(longs), 4):
            chunk = longs[i:i+4]
            f.write("  " + ", ".join(f"0x{w:08X}UL" for w in chunk) + ",\n")
        f.write("};\n")
    print(f"  wrote {path}  ({len(longs)} longs)")

def write_header_tiles_2d(path, var_name, tile_rows_per_tile, longs):
    """Emit array PROGMEM [NUM_TILES][N], pattern Galagino (brubber-like)."""
    n = len(longs) // tile_rows_per_tile
    with open(path, 'w') as f:
        f.write(f"// Auto-generated by romconv_arkangc.py\n")
        f.write(f"#define ARKANOID_NUM_TILES {n}\n")
        f.write(f"const unsigned long {var_name}[{n}][{tile_rows_per_tile}] PROGMEM = {{\n")
        for t in range(n):
            row_vals = longs[t*tile_rows_per_tile : (t+1)*tile_rows_per_tile]
            f.write("  { " + ", ".join(f"0x{w:08X}UL" for w in row_vals) + " },\n")
        f.write("};\n")
    print(f"  wrote {path}  ({n} tiles x {tile_rows_per_tile} rows)")

# ──────────────────────────────────────────────────────────────────────────
# Tile decode: 8x8 3bpp planar, 3 ROM da 32KB
#   charlayout MAME:
#     8,8, 4096, 3bpp, planes={2*32K*8, 32K*8, 0}, MSB-first dentro ogni byte
#     8 byte per char per plane
# ──────────────────────────────────────────────────────────────────────────
def decode_tiles(p0, p1, p2):
    n = len(p0) // 8
    tiles = []
    for t in range(n):
        tile = []
        for row in range(8):
            b0 = p0[t*8 + row]
            b1 = p1[t*8 + row]
            b2 = p2[t*8 + row]
            line = []
            for bit in range(7, -1, -1):
                px = ((b0 >> bit) & 1) | (((b1 >> bit) & 1) << 1) | (((b2 >> bit) & 1) << 2)
                line.append(px)
            tile.append(line)
        tiles.append(tile)
    return tiles

# Pack 8 px (3bpp) -> 32-bit long, 4 bit per pixel (formato Galagino)
def pack_row(px8):
    v = 0
    for i in range(8):
        v |= (px8[i] & 0x7) << (i * 4)
    return v

# ──────────────────────────────────────────────────────────────────────────
# Palette decode: 3 PROM RGB_444 -> 512 colori RGB565 byte-swap (BE)
#   ogni PROM byte: low nibble = 4-bit intensita' (MAME RGB_444_PROMS)
#   Espansione 4-bit -> 8-bit: x * 0x11
# ──────────────────────────────────────────────────────────────────────────
def decode_palette(prom_r, prom_g, prom_b):
    n = min(len(prom_r), len(prom_g), len(prom_b))
    out = []
    for i in range(n):
        r4 = prom_r[i] & 0x0F
        g4 = prom_g[i] & 0x0F
        b4 = prom_b[i] & 0x0F
        r8 = (r4 << 4) | r4
        g8 = (g4 << 4) | g4
        b8 = (b4 << 4) | b4
        rgb565 = ((r8 & 0xF8) << 8) | ((g8 & 0xFC) << 3) | (b8 >> 3)
        # ESP32 SPI: byte-swap BE
        out.append(((rgb565 & 0xFF) << 8) | (rgb565 >> 8))
    return out

# ──────────────────────────────────────────────────────────────────────────
# Main
# ──────────────────────────────────────────────────────────────────────────
def convert(zip_path, out_dir):
    print(f"[arkangc] {zip_path}  ->  {out_dir}")
    os.makedirs(out_dir, exist_ok=True)
    zf = zipfile.ZipFile(zip_path, 'r')
    names = set(zf.namelist())

    # alias dei nomi noti del set arkangc
    def pick(*candidates, size=None):
        for c in candidates:
            if c in names:
                return read_rom(zf, c, size)
        raise FileNotFoundError(f"none of {candidates} in {zip_path}")

    # 1) CPU ROM
    cpu1 = pick("arkgc.1", size=32768)
    cpu2 = pick("arkgc.2", size=32768)
    rom_cpu = bytearray(cpu1 + cpu2)  # 64KB totali (i secondi 32KB = banco/extra)
    write_header_bytes(os.path.join(out_dir, "arkanoid_rom_cpu.h"),
                       "arkanoid_rom_cpu", rom_cpu,
                       note="(arkgc.1 + arkgc.2 = 64KB)")

    # 2) GFX 8x8 3bpp
    gfx0 = pick("a75-03.rom", "a75-03.bin", size=32768)  # plane 0 (LSB)
    gfx1 = pick("a75-04.rom", "a75-04.bin", size=32768)  # plane 1
    gfx2 = pick("a75-05.rom", "a75-05.bin", size=32768)  # plane 2 (MSB)
    tiles = decode_tiles(gfx0, gfx1, gfx2)
    print(f"  decoded {len(tiles)} tiles 8x8 3bpp")

    # Pack: per ogni tile, 8 long (1 per riga) -> totale 4096*8 = 32768 long
    longs = []
    for tile in tiles:
        for row in tile:
            longs.append(pack_row(row))
    # Output formato Galagino [NUM_TILES][8] PROGMEM (compatibile blit_tile)
    write_header_tiles_2d(os.path.join(out_dir, "arkanoid_tilemap.h"),
                          "arkanoid_tilemap", 8, longs)

    # Sprite 16x16 = 4 char 2x2 (code, code+1, code+32, code+33).
    # I dati binari sono GLI STESSI di tilemap; il file spritemap.h emette
    # una macro/alias per chiarezza, e una tabella di "look-up" 16x16 packed.
    # Per semplicita', il driver in arkanoid.cpp riusera' direttamente
    # arkanoid_tilemap[] e assemblera' lo sprite a runtime.
    with open(os.path.join(out_dir, "arkanoid_spritemap.h"), 'w') as f:
        f.write("// Auto-generated by romconv_arkangc.py\n")
        f.write("// Arkanoid sprites = 4 char 8x8 (code, code+1, code+32, code+33)\n")
        f.write("// Assemblati a runtime in machines/arkanoid/arkanoid.cpp\n")
        f.write("#include \"arkanoid_tilemap.h\"\n")
        f.write("#define arkanoid_spritemap arkanoid_tilemap\n")
        f.write("#define arkanoid_spritemap_count arkanoid_tilemap_count\n")
    print(f"  wrote {os.path.join(out_dir, 'arkanoid_spritemap.h')}")

    # 3) Palette (3 PROM 4-bit RGB)
    prom_r = pick("a75-07.bpr", size=512)
    prom_g = pick("a75-08.bpr", size=512)
    prom_b = pick("a75-09.bpr", size=512)
    pal = decode_palette(prom_r, prom_g, prom_b)
    write_header_words(os.path.join(out_dir, "arkanoid_palette.h"),
                       "arkanoid_palette", pal)

    # 4) Logo placeholder (rigenerare con convert_arkanoid_logo.py separato)
    logo_path = os.path.join(out_dir, "arkanoid_logo.h")
    if not os.path.exists(logo_path):
        with open(logo_path, 'w') as f:
            f.write("// Placeholder logo — sostituisci con convert_arkanoid_logo.py\n")
            f.write("const unsigned short arkanoid_logo[] PROGMEM = { 0x0000 };\n")
        print(f"  wrote {logo_path}  (placeholder)")

    print("[arkangc] done.")


if __name__ == "__main__":
    if len(sys.argv) >= 3:
        zip_path = sys.argv[1]
        out_dir  = sys.argv[2]
    else:
        # default per il progetto SPINNERINO P4
        zip_path = str((Path.cwd() / ".." / "ROMS" / "arkangc.zip").resolve())
        out_dir  = str((Path.cwd() / ".." / "machines" / "arkanoid").resolve())
        print(f"Usage: {sys.argv[0]} <arkangc.zip> <output_dir>")
        print(f"Defaults:\n  zip = {zip_path}\n  out = {out_dir}\n")
    convert(zip_path, out_dir)
